Traceback (most recent call last):
  File "/root/mountainlionmovies/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/mountainlionmovies/manage.py", line 22, in <module>
    main()
  File "/root/mountainlionmovies/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/root/mountainlionmovies/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/mountainlionmovies/manage.py", line 22, in <module>
    main()
  File "/root/mountainlionmovies/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Watching for file changes with StatReloader
[30/Nov/2024 16:17:49] "GET / HTTP/1.1" 200 7598
[30/Nov/2024 16:17:49] "GET /static/styles1.css HTTP/1.1" 200 15894
[30/Nov/2024 16:17:49] "GET /static/static.js HTTP/1.1" 200 1140
[30/Nov/2024 16:17:49] "GET /static/scripts/notifications.js HTTP/1.1" 200 3285
[30/Nov/2024 16:17:49] "GET /static/images/menu.png HTTP/1.1" 200 46203
[30/Nov/2024 16:17:50] "GET /static/images/mountain_lion.png HTTP/1.1" 200 13602
[30/Nov/2024 16:17:50] "GET /static/images/newMountionLionLogo.png HTTP/1.1" 200 128112
[30/Nov/2024 16:17:50] "GET /static/images/usericon1.png HTTP/1.1" 200 38073
[30/Nov/2024 16:17:50] "GET /static/images/bell.png HTTP/1.1" 200 250152
[30/Nov/2024 16:29:50] "GET / HTTP/1.1" 200 7598
[30/Nov/2024 16:29:50] "GET /static/styles1.css HTTP/1.1" 200 15894
[30/Nov/2024 16:29:50] "GET /static/scripts/notifications.js HTTP/1.1" 200 3285
[30/Nov/2024 16:29:50] "GET /static/static.js HTTP/1.1" 200 1140
[30/Nov/2024 16:29:50] "GET /static/images/menu.png HTTP/1.1" 200 46203
[30/Nov/2024 16:29:51] "GET /static/images/newMountionLionLogo.png HTTP/1.1" 200 128112
[30/Nov/2024 16:29:52] "GET /static/images/usericon1.png HTTP/1.1" 200 38073
[30/Nov/2024 16:29:53] "GET /static/images/mountain_lion.png HTTP/1.1" 200 13602
[30/Nov/2024 16:29:53] "GET /static/images/bell.png HTTP/1.1" 200 250152
Forbidden: /api/notifications/
[30/Nov/2024 16:29:57] "GET /api/notifications/ HTTP/1.1" 403 58
Not Found: /apple-touch-icon.png
[30/Nov/2024 16:30:21] "GET /apple-touch-icon.png HTTP/1.1" 404 13069
Not Found: /apple-touch-icon-precomposed.png
[30/Nov/2024 16:30:21] "GET / HTTP/1.1" 200 7598
Not Found: /apple-touch-icon.png
[30/Nov/2024 16:30:21] "GET / HTTP/1.1" 200 7598
[30/Nov/2024 16:30:21] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 13105
[30/Nov/2024 16:30:21] "GET /apple-touch-icon.png HTTP/1.1" 404 13069
Not Found: /favicon.ico
[30/Nov/2024 16:30:21] "GET /favicon.ico HTTP/1.1" 404 13042
Not Found: /apple-touch-icon-precomposed.png
[30/Nov/2024 16:30:21] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 13105
Not Found: /favicon.ico
[30/Nov/2024 16:30:21] "GET /favicon.ico HTTP/1.1" 404 13042
[30/Nov/2024 16:30:22] "GET /static/images/favicon.ico HTTP/1.1" 200 15406
[30/Nov/2024 16:30:23] "GET /static/images/favicon.ico HTTP/1.1" 200 15406
[30/Nov/2024 16:30:23] "GET /static/images/favicon.ico HTTP/1.1" 200 15406
[30/Nov/2024 16:30:24] "GET / HTTP/1.1" 200 7598
[30/Nov/2024 16:30:25] "GET /static/images/favicon.ico HTTP/1.1" 200 15406
[30/Nov/2024 16:43:28] "GET / HTTP/1.1" 200 7598
Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
Bad Request: /example.com:443
[30/Nov/2024 16:43:53] "CONNECT example.com:443 HTTP/1.1" 400 64445
Not Found: /favicon.ico
[30/Nov/2024 16:50:07] "GET /favicon.ico HTTP/1.1" 404 13042
[30/Nov/2024 19:40:15] "GET / HTTP/1.0" 200 7598
[30/Nov/2024 19:44:26] "GET / HTTP/1.1" 200 7598
Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
Bad Request: /example.com:443
[30/Nov/2024 20:50:54] "CONNECT example.com:443 HTTP/1.1" 400 64445
[30/Nov/2024 20:51:48] "GET / HTTP/1.1" 200 7598
[30/Nov/2024 20:51:48] "GET /static/images/newMountionLionLogo.png HTTP/1.1" 304 0
[30/Nov/2024 20:51:48] "GET /static/images/menu.png HTTP/1.1" 304 0
[30/Nov/2024 20:51:48] "GET /static/images/mountain_lion.png HTTP/1.1" 304 0
[30/Nov/2024 20:51:48] "GET /static/static.js HTTP/1.1" 304 0
[30/Nov/2024 20:51:48] "GET /static/images/usericon1.png HTTP/1.1" 304 0
[30/Nov/2024 20:51:48] "GET /static/styles1.css HTTP/1.1" 304 0
[30/Nov/2024 20:51:48] "GET /static/images/bell.png HTTP/1.1" 304 0
[30/Nov/2024 20:51:48] "GET /static/scripts/notifications.js HTTP/1.1" 304 0
[30/Nov/2024 20:51:52,089] - Broken pipe from ('75.70.236.224', 51439)
[30/Nov/2024 20:51:52,089] - Broken pipe from ('75.70.236.224', 19426)
[30/Nov/2024 20:51:52,089] - Broken pipe from ('75.70.236.224', 1826)
[30/Nov/2024 20:51:52,089] - Broken pipe from ('75.70.236.224', 28428)
[30/Nov/2024 20:51:52,089] - Broken pipe from ('75.70.236.224', 23146)
[30/Nov/2024 20:51:53,084] - Broken pipe from ('75.70.236.224', 3079)
[30/Nov/2024 22:43:48] code 400, message Bad request version ('á^\x14µ©D2\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
[30/Nov/2024 22:43:48] You're accessing the development server over HTTPS, but it only supports HTTP.
[30/Nov/2024 22:43:50] "GET / HTTP/1.1" 200 7598
[30/Nov/2024 22:43:50] "GET /static/styles1.css HTTP/1.1" 200 15894
[30/Nov/2024 22:43:50] "GET /static/static.js HTTP/1.1" 200 1140
[30/Nov/2024 22:43:50] "GET /static/scripts/notifications.js HTTP/1.1" 200 3285
[30/Nov/2024 22:43:51] "GET /static/images/mountain_lion.png HTTP/1.1" 200 13602
[30/Nov/2024 22:43:51] "GET /static/images/newMountionLionLogo.png HTTP/1.1" 200 128112
[30/Nov/2024 22:43:51] "GET /static/images/usericon1.png HTTP/1.1" 200 38073
[30/Nov/2024 22:43:51] "GET /static/images/menu.png HTTP/1.1" 200 46203
[30/Nov/2024 22:43:51] "GET /static/images/bell.png HTTP/1.1" 200 250152
[30/Nov/2024 22:43:51] "GET /static/images/favicon.ico HTTP/1.1" 200 15406
[30/Nov/2024 22:46:29] code 400, message Bad request version ('\x13_ê"MJ£ßä^3H]<oa7§£\x99³\x05ê÷ÞÞ\x89QK\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
[30/Nov/2024 22:46:29] You're accessing the development server over HTTPS, but it only supports HTTP.
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /
[30/Nov/2024 22:46:31] "GET / HTTP/1.1" 400 66698
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[30/Nov/2024 22:46:32] "GET /favicon.ico HTTP/1.1" 400 66680
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /
[30/Nov/2024 22:46:57] "GET / HTTP/1.1" 400 64637
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /
[30/Nov/2024 22:47:18] "GET / HTTP/1.1" 400 66698
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /
[30/Nov/2024 22:49:52] "GET / HTTP/1.1" 400 66698
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /
[30/Nov/2024 22:50:51] "GET / HTTP/1.1" 400 65588
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /
[30/Nov/2024 22:51:01] "GET / HTTP/1.1" 400 66698
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /
[30/Nov/2024 22:55:45] "GET / HTTP/1.1" 400 66698
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /
[30/Nov/2024 22:56:39] "GET / HTTP/1.1" 400 66698
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /
[30/Nov/2024 22:56:47] "GET / HTTP/1.1" 400 66698
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /
[30/Nov/2024 22:57:09] "GET / HTTP/1.1" 400 65621
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /
[30/Nov/2024 22:57:15] "GET / HTTP/1.1" 400 66698
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /
[30/Nov/2024 23:01:23] "GET / HTTP/1.1" 400 66698
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /
[30/Nov/2024 23:18:38] "GET / HTTP/1.1" 400 65826
Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mountainlionmovies.com:8000'. You may need to add 'mountainlionmovies.com' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[30/Nov/2024 23:18:39] "GET /favicon.ico HTTP/1.1" 400 65854
/root/mountainlionmovies/django_project/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
November 30, 2024 - 16:17:27
Django version 5.1.2, using settings 'django_project.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
[30/Nov/2024 23:19:02] "GET / HTTP/1.1" 200 7598
[30/Nov/2024 23:19:02] "GET /static/styles1.css HTTP/1.1" 200 15894
[30/Nov/2024 23:19:02] "GET /static/scripts/notifications.js HTTP/1.1" 200 3285
[30/Nov/2024 23:19:02] "GET /static/static.js HTTP/1.1" 200 1140
[30/Nov/2024 23:19:02] "GET /static/images/newMountionLionLogo.png HTTP/1.1" 200 128112
[30/Nov/2024 23:19:02] "GET /static/images/mountain_lion.png HTTP/1.1" 200 13602
[30/Nov/2024 23:19:02] "GET /static/images/menu.png HTTP/1.1" 200 46203
[30/Nov/2024 23:19:02] "GET /static/images/usericon1.png HTTP/1.1" 200 38073
[30/Nov/2024 23:19:02] "GET /static/images/bell.png HTTP/1.1" 200 250152
[30/Nov/2024 23:19:03] "GET /static/images/favicon.ico HTTP/1.1" 200 15406
[30/Nov/2024 23:22:41] "GET / HTTP/1.1" 200 7598
[30/Nov/2024 23:22:41] "GET /static/styles1.css HTTP/1.1" 200 15894
[30/Nov/2024 23:22:41] "GET /static/scripts/notifications.js HTTP/1.1" 200 3285
[30/Nov/2024 23:22:41] "GET /static/static.js HTTP/1.1" 200 1140
[30/Nov/2024 23:22:41] "GET /static/images/newMountionLionLogo.png HTTP/1.1" 200 128112
[30/Nov/2024 23:22:41] "GET /static/images/menu.png HTTP/1.1" 200 46203
[30/Nov/2024 23:22:41] "GET /static/images/usericon1.png HTTP/1.1" 200 38073
[30/Nov/2024 23:22:41] "GET /static/images/mountain_lion.png HTTP/1.1" 200 13602
[30/Nov/2024 23:22:41] "GET /static/images/bell.png HTTP/1.1" 200 250152
[30/Nov/2024 23:22:46] "GET /login/ HTTP/1.1" 200 6818
[30/Nov/2024 23:22:49] "GET /login/ HTTP/1.1" 200 6818
[30/Nov/2024 23:22:49] "GET /static/static.js HTTP/1.1" 200 1140
[30/Nov/2024 23:22:49] "GET /static/styles1.css HTTP/1.1" 200 15894
[30/Nov/2024 23:22:49] "GET /static/scripts/notifications.js HTTP/1.1" 200 3285
[30/Nov/2024 23:22:49] "GET /static/images/menu.png HTTP/1.1" 200 46203
[30/Nov/2024 23:22:49] "GET /static/scripts/notifications.js HTTP/1.1" 200 3285
[30/Nov/2024 23:22:49] "GET /static/images/newMountionLionLogo.png HTTP/1.1" 200 128112
[30/Nov/2024 23:22:50] "GET /static/images/usericon1.png HTTP/1.1" 200 38073
[30/Nov/2024 23:22:50] "GET /static/images/bell.png HTTP/1.1" 200 250152
[30/Nov/2024 23:22:50] "GET /static/images/newMountionLionLogo.png HTTP/1.1" 200 128112
[30/Nov/2024 23:22:50] "GET /static/images/menu.png HTTP/1.1" 200 46203
[30/Nov/2024 23:22:50] "GET /static/images/usericon1.png HTTP/1.1" 200 38073
[30/Nov/2024 23:22:50] "GET /static/images/bell.png HTTP/1.1" 200 250152
[30/Nov/2024 23:22:52] "GET /register/ HTTP/1.1" 200 7443
[30/Nov/2024 23:22:52] "GET /static/scripts/passwordHidden.js HTTP/1.1" 200 1376
Internal Server Error: /register/
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/filmproject/views/profile_views.py", line 231, in register
    testSend = send_mail(
               ^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/mail/__init__.py", line 88, in send_mail
    return mail.send()
           ^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/mail/message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/mail/backends/smtp.py", line 128, in send_messages
    new_conn_created = self.open()
                       ^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/mail/backends/smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python3.12/smtplib.py", line 750, in login
    raise last_exception
  File "/usr/lib/python3.12/smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-2153a1e3e7bsm37537725ad.25 - gsmtp')
[30/Nov/2024 23:23:14] "POST /register/ HTTP/1.1" 500 100049
[01/Dec/2024 00:39:45] "GET / HTTP/1.1" 200 7598
[01/Dec/2024 00:39:45] "GET /static/styles1.css HTTP/1.1" 200 15894
[01/Dec/2024 00:39:45] "GET /static/static.js HTTP/1.1" 200 1140
[01/Dec/2024 00:39:45] "GET /static/scripts/notifications.js HTTP/1.1" 200 3285
[01/Dec/2024 00:39:45] "GET /static/images/newMountionLionLogo.png HTTP/1.1" 200 128112
[01/Dec/2024 00:39:45] "GET /static/images/menu.png HTTP/1.1" 200 46203
[01/Dec/2024 00:39:45] "GET /static/images/bell.png HTTP/1.1" 200 250152
[01/Dec/2024 00:39:45] "GET /static/images/usericon1.png HTTP/1.1" 200 38073
[01/Dec/2024 00:39:45] "GET /static/images/mountain_lion.png HTTP/1.1" 200 13602
[01/Dec/2024 00:39:45] "GET /static/images/favicon.ico HTTP/1.1" 200 15406
Forbidden: /api/notifications/
[01/Dec/2024 00:39:46] "GET /api/notifications/ HTTP/1.1" 403 58
[01/Dec/2024 00:39:49] "GET /login/ HTTP/1.1" 200 6818
[01/Dec/2024 00:39:50] "GET /register/ HTTP/1.1" 200 7443
[01/Dec/2024 00:39:50] "GET /static/scripts/passwordHidden.js HTTP/1.1" 200 1376
[01/Dec/2024 00:40:06] "POST /register/ HTTP/1.1" 200 8024
Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
Bad Request: /example.com:443
[01/Dec/2024 00:51:45] "CONNECT example.com:443 HTTP/1.1" 400 64525
[01/Dec/2024 03:58:57] "GET / HTTP/1.1" 200 7598
Not Found: /favicon.ico
[01/Dec/2024 03:59:11] "GET /favicon.ico HTTP/1.1" 404 13042
Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Bad Request: /http:/api.ipify.org/
[01/Dec/2024 03:59:17] "GET http://api.ipify.org/?format=json HTTP/1.1" 400 65173
Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Bad Request: /www.shadowserver.org:443
[01/Dec/2024 03:59:20] "CONNECT www.shadowserver.org:443 HTTP/1.1" 400 65353
Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
Bad Request: /example.com:443
[01/Dec/2024 04:33:27] "CONNECT example.com:443 HTTP/1.1" 400 64525
[01/Dec/2024 06:28:49] code 400, message Bad request version ('!')
[01/Dec/2024 06:28:49] You're accessing the development server over HTTPS, but it only supports HTTP.
[01/Dec/2024 07:32:03] code 400, message Bad request version ('OÑËÜ®Ëd')
[01/Dec/2024 07:32:03] "   TZ         .    I¨À )z» zÚf Ò~Uñi»©                ÃÐ¢|¦v½óOÑËÜ®Ëd" 400 -
[01/Dec/2024 07:32:37] code 400, message Bad request version ('OÑËÜ®Ëd')
[01/Dec/2024 07:32:37] "   TZ         .    I¨À )z» zÚf Ò~Uñi»©                ÃÐ¢|¦v½óOÑËÜ®Ëd" 400 -
[01/Dec/2024 07:51:39] "GET / HTTP/1.1" 200 7598
Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
Bad Request: /example.com:443
[01/Dec/2024 08:39:13] "CONNECT example.com:443 HTTP/1.1" 400 64525
[01/Dec/2024 10:55:45] "GET / HTTP/1.1" 200 7598
[01/Dec/2024 12:37:19] code 400, message Bad HTTP/0.9 request type ('\x00\x00\x00')
[01/Dec/2024 12:37:19] "    c                           " 400 -
Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
Bad Request: /example.com:443
[01/Dec/2024 12:47:35] "CONNECT example.com:443 HTTP/1.1" 400 64525
/root/mountainlionmovies/django_project/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
November 30, 2024 - 23:19:02
Django version 5.1.2, using settings 'django_project.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

Sending email to: mayberrykory27@gmail.com
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/db/utils.py", line 113, in load_backend
    return import_module("%s.base" % backend_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django.db.postgresql_psycopg2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 126, in inner_run
    autoreload.raise_last_exception()
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/contrib/auth/models.py", line 5, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/contrib/auth/base_user.py", line 40, in <module>
    class AbstractBaseUser(models.Model):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/db/models/base.py", line 143, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/db/models/base.py", line 371, in add_to_class
    value.contribute_to_class(cls, name)
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/db/models/options.py", line 231, in contribute_to_class
    self.db_table, connection.ops.max_name_length()
                   ^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/db/utils.py", line 193, in create_connection
    backend = load_backend(db["ENGINE"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/db/utils.py", line 126, in load_backend
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: 'django.db.postgresql_psycopg2' isn't an available database backend or couldn't be imported. Check the above exception. To use one of the built-in backends, use 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
/root/mountainlionmovies/django_project/settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/db/utils.py", line 113, in load_backend
    return import_module("%s.base" % backend_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django.db.postgresql_psycopg2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 126, in inner_run
    autoreload.raise_last_exception()
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/contrib/auth/models.py", line 5, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/contrib/auth/base_user.py", line 40, in <module>
    class AbstractBaseUser(models.Model):
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/db/models/base.py", line 143, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/db/models/base.py", line 371, in add_to_class
    value.contribute_to_class(cls, name)
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/db/models/options.py", line 231, in contribute_to_class
    self.db_table, connection.ops.max_name_length()
                   ^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/db/utils.py", line 193, in create_connection
    backend = load_backend(db["ENGINE"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mountainlionmovies/venv/lib/python3.12/site-packages/django/db/utils.py", line 126, in load_backend
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: 'django.db.postgresql_psycopg2' isn't an available database backend or couldn't be imported. Check the above exception. To use one of the built-in backends, use 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
/root/mountainlionmovies/django_project/settings.py changed, reloading.
Watching for file changes with StatReloader
